/**
 *
 * $Id$
 */
package cloud_computing.validation;

import cloud_computing.SecurityGroup;
import cloud_computing.Subred;
import cloud_computing.TamanoMaquina;
import cloud_computing.VPC;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link cloud_computing.Servidor}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ServidorValidator {
	boolean validate();

	boolean validateNombre(String value);
	boolean validateTamanoM(TamanoMaquina value);
	boolean validateVpc(VPC value);
	boolean validateSubred(Subred value);
	boolean validateServersecuritygroup(EList<SecurityGroup> value);
}
