/**
 *
 * $Id$
 */
package cloud_computing.validation;

import cloud_computing.SistemaOperativo;

/**
 * A sample validator interface for {@link cloud_computing.ServidorAplicacion}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ServidorAplicacionValidator {
	boolean validate();

	boolean validateSistemaO(SistemaOperativo value);
}
