/**
 *
 * $Id$
 */
package cloud_computing.validation;


/**
 * A sample validator interface for {@link cloud_computing.Subred}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SubredValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateCidr(String value);
	boolean validateAz(String value);
}
