/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Inject
	private MyDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getServidorAccess().getAlternatives(), "rule__Servidor__Alternatives");
					put(grammarAccess.getProveedorServicioAccess().getAlternatives(), "rule__ProveedorServicio__Alternatives");
					put(grammarAccess.getAmbienteAccess().getAlternatives(), "rule__Ambiente__Alternatives");
					put(grammarAccess.getTamanoMaquinaAccess().getAlternatives(), "rule__TamanoMaquina__Alternatives");
					put(grammarAccess.getSistemaOperativoAccess().getAlternatives(), "rule__SistemaOperativo__Alternatives");
					put(grammarAccess.getSistemaManejadorAccess().getAlternatives(), "rule__SistemaManejador__Alternatives");
					put(grammarAccess.getInfraestructuraAccess().getGroup(), "rule__Infraestructura__Group__0");
					put(grammarAccess.getInfraestructuraAccess().getGroup_4(), "rule__Infraestructura__Group_4__0");
					put(grammarAccess.getInfraestructuraAccess().getGroup_6(), "rule__Infraestructura__Group_6__0");
					put(grammarAccess.getInfraestructuraAccess().getGroup_8(), "rule__Infraestructura__Group_8__0");
					put(grammarAccess.getInfraestructuraAccess().getGroup_8_4(), "rule__Infraestructura__Group_8_4__0");
					put(grammarAccess.getInfraestructuraAccess().getGroup_10(), "rule__Infraestructura__Group_10__0");
					put(grammarAccess.getInfraestructuraAccess().getGroup_10_4(), "rule__Infraestructura__Group_10_4__0");
					put(grammarAccess.getLoginAccess().getGroup(), "rule__Login__Group__0");
					put(grammarAccess.getLoginAccess().getGroup_2(), "rule__Login__Group_2__0");
					put(grammarAccess.getLoginAccess().getGroup_3(), "rule__Login__Group_3__0");
					put(grammarAccess.getLoginAccess().getGroup_4(), "rule__Login__Group_4__0");
					put(grammarAccess.getLoginAccess().getGroup_5(), "rule__Login__Group_5__0");
					put(grammarAccess.getLoginAccess().getGroup_6(), "rule__Login__Group_6__0");
					put(grammarAccess.getAmbienteDesplegueAccess().getGroup(), "rule__AmbienteDesplegue__Group__0");
					put(grammarAccess.getAmbienteDesplegueAccess().getGroup_2(), "rule__AmbienteDesplegue__Group_2__0");
					put(grammarAccess.getAmbienteDesplegueAccess().getGroup_4(), "rule__AmbienteDesplegue__Group_4__0");
					put(grammarAccess.getAmbienteDesplegueAccess().getGroup_6(), "rule__AmbienteDesplegue__Group_6__0");
					put(grammarAccess.getAmbienteDesplegueAccess().getGroup_6_4(), "rule__AmbienteDesplegue__Group_6_4__0");
					put(grammarAccess.getAmbienteDesplegueAccess().getGroup_12(), "rule__AmbienteDesplegue__Group_12__0");
					put(grammarAccess.getAmbienteDesplegueAccess().getGroup_15(), "rule__AmbienteDesplegue__Group_15__0");
					put(grammarAccess.getAmbienteDesplegueAccess().getGroup_15_4(), "rule__AmbienteDesplegue__Group_15_4__0");
					put(grammarAccess.getSecurityGroupAccess().getGroup(), "rule__SecurityGroup__Group__0");
					put(grammarAccess.getSecurityGroupAccess().getGroup_2(), "rule__SecurityGroup__Group_2__0");
					put(grammarAccess.getSecurityGroupAccess().getGroup_4(), "rule__SecurityGroup__Group_4__0");
					put(grammarAccess.getSubredAccess().getGroup(), "rule__Subred__Group__0");
					put(grammarAccess.getSubredAccess().getGroup_2(), "rule__Subred__Group_2__0");
					put(grammarAccess.getSubredAccess().getGroup_4(), "rule__Subred__Group_4__0");
					put(grammarAccess.getSubredAccess().getGroup_6(), "rule__Subred__Group_6__0");
					put(grammarAccess.getVPCAccess().getGroup(), "rule__VPC__Group__0");
					put(grammarAccess.getVPCAccess().getGroup_2(), "rule__VPC__Group_2__0");
					put(grammarAccess.getVPCAccess().getGroup_4(), "rule__VPC__Group_4__0");
					put(grammarAccess.getServidorAplicacionAccess().getGroup(), "rule__ServidorAplicacion__Group__0");
					put(grammarAccess.getServidorAplicacionAccess().getGroup_6(), "rule__ServidorAplicacion__Group_6__0");
					put(grammarAccess.getServidorAplicacionAccess().getGroup_8(), "rule__ServidorAplicacion__Group_8__0");
					put(grammarAccess.getServidorAplicacionAccess().getGroup_10(), "rule__ServidorAplicacion__Group_10__0");
					put(grammarAccess.getServidorBaseDeDatosAccess().getGroup(), "rule__ServidorBaseDeDatos__Group__0");
					put(grammarAccess.getServidorBaseDeDatosAccess().getGroup_6(), "rule__ServidorBaseDeDatos__Group_6__0");
					put(grammarAccess.getServidorBaseDeDatosAccess().getGroup_8(), "rule__ServidorBaseDeDatos__Group_8__0");
					put(grammarAccess.getServidorBaseDeDatosAccess().getGroup_10(), "rule__ServidorBaseDeDatos__Group_10__0");
					put(grammarAccess.getServidorAlmacenamientoAccess().getGroup(), "rule__ServidorAlmacenamiento__Group__0");
					put(grammarAccess.getServidorAlmacenamientoAccess().getGroup_6(), "rule__ServidorAlmacenamiento__Group_6__0");
					put(grammarAccess.getServidorAlmacenamientoAccess().getGroup_8(), "rule__ServidorAlmacenamiento__Group_8__0");
					put(grammarAccess.getServidorAlmacenamientoAccess().getGroup_10(), "rule__ServidorAlmacenamiento__Group_10__0");
					put(grammarAccess.getConexionAccess().getGroup(), "rule__Conexion__Group__0");
					put(grammarAccess.getInfraestructuraAccess().getNombreProyectoAssignment_2(), "rule__Infraestructura__NombreProyectoAssignment_2");
					put(grammarAccess.getInfraestructuraAccess().getTipoAssignment_4_2(), "rule__Infraestructura__TipoAssignment_4_2");
					put(grammarAccess.getInfraestructuraAccess().getLoginsAssignment_6_2(), "rule__Infraestructura__LoginsAssignment_6_2");
					put(grammarAccess.getInfraestructuraAccess().getSecuritygroupsAssignment_8_3(), "rule__Infraestructura__SecuritygroupsAssignment_8_3");
					put(grammarAccess.getInfraestructuraAccess().getSecuritygroupsAssignment_8_4_1(), "rule__Infraestructura__SecuritygroupsAssignment_8_4_1");
					put(grammarAccess.getInfraestructuraAccess().getAmbientesdesplegueAssignment_10_3(), "rule__Infraestructura__AmbientesdesplegueAssignment_10_3");
					put(grammarAccess.getInfraestructuraAccess().getAmbientesdesplegueAssignment_10_4_1(), "rule__Infraestructura__AmbientesdesplegueAssignment_10_4_1");
					put(grammarAccess.getLoginAccess().getNombreConexionAssignment_2_2(), "rule__Login__NombreConexionAssignment_2_2");
					put(grammarAccess.getLoginAccess().getUsuarioAssignment_3_2(), "rule__Login__UsuarioAssignment_3_2");
					put(grammarAccess.getLoginAccess().getContrasenaAssignment_4_2(), "rule__Login__ContrasenaAssignment_4_2");
					put(grammarAccess.getLoginAccess().getAccessIdAssignment_5_2(), "rule__Login__AccessIdAssignment_5_2");
					put(grammarAccess.getLoginAccess().getSecretAssignment_6_2(), "rule__Login__SecretAssignment_6_2");
					put(grammarAccess.getAmbienteDesplegueAccess().getAliasAssignment_2_2(), "rule__AmbienteDesplegue__AliasAssignment_2_2");
					put(grammarAccess.getAmbienteDesplegueAccess().getTipoAmbienteAssignment_4_2(), "rule__AmbienteDesplegue__TipoAmbienteAssignment_4_2");
					put(grammarAccess.getAmbienteDesplegueAccess().getVpcAssignment_6_3(), "rule__AmbienteDesplegue__VpcAssignment_6_3");
					put(grammarAccess.getAmbienteDesplegueAccess().getVpcAssignment_6_4_1(), "rule__AmbienteDesplegue__VpcAssignment_6_4_1");
					put(grammarAccess.getAmbienteDesplegueAccess().getServidoresAssignment_11(), "rule__AmbienteDesplegue__ServidoresAssignment_11");
					put(grammarAccess.getAmbienteDesplegueAccess().getServidoresAssignment_12_1(), "rule__AmbienteDesplegue__ServidoresAssignment_12_1");
					put(grammarAccess.getAmbienteDesplegueAccess().getConexionAssignment_15_3(), "rule__AmbienteDesplegue__ConexionAssignment_15_3");
					put(grammarAccess.getAmbienteDesplegueAccess().getConexionAssignment_15_4_1(), "rule__AmbienteDesplegue__ConexionAssignment_15_4_1");
					put(grammarAccess.getSecurityGroupAccess().getNameAssignment_2_2(), "rule__SecurityGroup__NameAssignment_2_2");
					put(grammarAccess.getSecurityGroupAccess().getDescriptionAssignment_4_2(), "rule__SecurityGroup__DescriptionAssignment_4_2");
					put(grammarAccess.getSubredAccess().getNameAssignment_2_2(), "rule__Subred__NameAssignment_2_2");
					put(grammarAccess.getSubredAccess().getCidrAssignment_4_2(), "rule__Subred__CidrAssignment_4_2");
					put(grammarAccess.getSubredAccess().getAzAssignment_6_2(), "rule__Subred__AzAssignment_6_2");
					put(grammarAccess.getVPCAccess().getNameAssignment_2_2(), "rule__VPC__NameAssignment_2_2");
					put(grammarAccess.getVPCAccess().getSubredAssignment_4_2(), "rule__VPC__SubredAssignment_4_2");
					put(grammarAccess.getServidorAplicacionAccess().getNombreAssignment_6_2(), "rule__ServidorAplicacion__NombreAssignment_6_2");
					put(grammarAccess.getServidorAplicacionAccess().getTamanoMAssignment_8_2(), "rule__ServidorAplicacion__TamanoMAssignment_8_2");
					put(grammarAccess.getServidorAplicacionAccess().getSistemaOAssignment_10_2(), "rule__ServidorAplicacion__SistemaOAssignment_10_2");
					put(grammarAccess.getServidorAplicacionAccess().getVpcAssignment_14(), "rule__ServidorAplicacion__VpcAssignment_14");
					put(grammarAccess.getServidorAplicacionAccess().getSubredAssignment_18(), "rule__ServidorAplicacion__SubredAssignment_18");
					put(grammarAccess.getServidorAplicacionAccess().getServersecuritygroupAssignment_22(), "rule__ServidorAplicacion__ServersecuritygroupAssignment_22");
					put(grammarAccess.getServidorBaseDeDatosAccess().getNombreAssignment_6_2(), "rule__ServidorBaseDeDatos__NombreAssignment_6_2");
					put(grammarAccess.getServidorBaseDeDatosAccess().getTamanoMAssignment_8_2(), "rule__ServidorBaseDeDatos__TamanoMAssignment_8_2");
					put(grammarAccess.getServidorBaseDeDatosAccess().getSistemaManejadorAssignment_10_2(), "rule__ServidorBaseDeDatos__SistemaManejadorAssignment_10_2");
					put(grammarAccess.getServidorBaseDeDatosAccess().getVpcAssignment_14(), "rule__ServidorBaseDeDatos__VpcAssignment_14");
					put(grammarAccess.getServidorBaseDeDatosAccess().getSubredAssignment_18(), "rule__ServidorBaseDeDatos__SubredAssignment_18");
					put(grammarAccess.getServidorBaseDeDatosAccess().getServersecuritygroupAssignment_22(), "rule__ServidorBaseDeDatos__ServersecuritygroupAssignment_22");
					put(grammarAccess.getServidorAlmacenamientoAccess().getNombreAssignment_6_2(), "rule__ServidorAlmacenamiento__NombreAssignment_6_2");
					put(grammarAccess.getServidorAlmacenamientoAccess().getTamanoMAssignment_8_2(), "rule__ServidorAlmacenamiento__TamanoMAssignment_8_2");
					put(grammarAccess.getServidorAlmacenamientoAccess().getTamanoInicialAssignment_10_2(), "rule__ServidorAlmacenamiento__TamanoInicialAssignment_10_2");
					put(grammarAccess.getServidorAlmacenamientoAccess().getVpcAssignment_14(), "rule__ServidorAlmacenamiento__VpcAssignment_14");
					put(grammarAccess.getServidorAlmacenamientoAccess().getSubredAssignment_18(), "rule__ServidorAlmacenamiento__SubredAssignment_18");
					put(grammarAccess.getServidorAlmacenamientoAccess().getServersecuritygroupAssignment_22(), "rule__ServidorAlmacenamiento__ServersecuritygroupAssignment_22");
					put(grammarAccess.getConexionAccess().getServidor1Assignment_4(), "rule__Conexion__Servidor1Assignment_4");
					put(grammarAccess.getConexionAccess().getServidor2Assignment_8(), "rule__Conexion__Servidor2Assignment_8");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
