/**
 *
 * $Id$
 */
package cloud_computing.validation;

import cloud_computing.Ambiente;
import cloud_computing.Conexion;
import cloud_computing.Servidor;
import cloud_computing.VPC;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link cloud_computing.AmbienteDesplegue}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AmbienteDesplegueValidator {
	boolean validate();

	boolean validateTipoAmbiente(Ambiente value);
	boolean validateAlias(String value);
	boolean validateServidores(EList<Servidor> value);
	boolean validateVpc(EList<VPC> value);
	boolean validateConexion(EList<Conexion> value);
}
