/**
 *
 * $Id$
 */
package cloud_computing.validation;


/**
 * A sample validator interface for {@link cloud_computing.Rules}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RulesValidator {
	boolean validate();

	boolean validateType(String value);
	boolean validateProtocol(String value);
	boolean validatePortRange(String value);
	boolean validateSource(String value);
	boolean validateDescription(String value);
}
